# Generated by Django 5.2.11 on 2026-05-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='', upload_to='produtos/'),
            preserve_default=False,
        ),
    ]
